/* This file was auto-generated by the gen_resfiles utility and
   should not be edited directly.  Modify the master resource list
   instead and regenerate. */

#define KOHR_AH_ICON_MASK_PMAP_ANIM 0x57c00302L
#define KOHR_AH_MICON_MASK_PMAP_ANIM 0x57c00402L
#define KOHR_AH_BIG_MASK_PMAP_ANIM 0x57c00502L
#define KOHR_AH_MED_MASK_PMAP_ANIM 0x57c00602L
#define KOHR_AH_SML_MASK_PMAP_ANIM 0x57c00702L
#define BUZZSAW_BIG_MASK_PMAP_ANIM 0x57c00802L
#define BUZZSAW_MED_MASK_PMAP_ANIM 0x57c00902L
#define BUZZSAW_SML_MASK_PMAP_ANIM 0x57c00a02L
#define GAS_BIG_MASK_PMAP_ANIM 0x57c00b02L
#define GAS_MED_MASK_PMAP_ANIM 0x57c00c02L
#define GAS_SML_MASK_PMAP_ANIM 0x57c00d02L
#define KOHR_AH_CAPTAIN_MASK_PMAP_ANIM 0x57c00e02L
