/* This file was auto-generated by the gen_resfiles utility and
   should not be edited directly.  Modify the master resource list
   instead and regenerate. */

#define KOHR_AH_SHIP_SOUNDS 0x57c00205L
