/* This file was auto-generated by the gen_resfiles utility and
   should not be edited directly.  Modify the master resource list
   instead and regenerate. */

#define KOHR_AH_RACE_STRINGS 0x57c00104L
