/* This file was auto-generated by the gen_resfiles utility and
   should not be edited directly.  Modify the master resource list
   instead and regenerate. */

#define COMMANDER_COLOR_MAP "comm.commander.colortable"
#define COMMANDER_CONVERSATION_PHRASES "comm.commander.dialogue"
#define STARBASE_CONVERSATION_PHRASES "comm.starbase.dialogue"
