/* This file was auto-generated by the gen_resfiles utility and
   should not be edited directly.  Modify the master resource list
   instead and regenerate. */

#define COMMANDER_MUSIC 0x3ee00006L
#define STARBASE_ALT_MUSIC 0x3ee00106L
#define COMMANDER_LOWPOW_MUSIC 0x3ee00206L
