/* This file was auto-generated by the gen_resfiles utility and
   should not be edited directly.  Modify the master resource list
   instead and regenerate. */

#define COMMANDER_COLOR_MAP 0x3ee00404L
#define COMMANDER_CONVERSATION_PHRASES 0x3ee00504L
#define STARBASE_CONVERSATION_PHRASES 0x3ee00604L
