/* This file was auto-generated by the gen_resfiles utility and
   should not be edited directly.  Modify the master resource list
   instead and regenerate. */

#define SIS_VICTORY_SONG "ship.sis_ship.ditty"
