/* This file was auto-generated by the gen_resfiles utility and
   should not be edited directly.  Modify the master resource list
   instead and regenerate. */

#define YEHAT_MUSIC 0x41400006L
#define REBEL_MUSIC 0x41400106L
