/* This file was auto-generated by the gen_resfiles utility and
   should not be edited directly.  Modify the master resource list
   instead and regenerate. */

#define YEHAT_CONVERSATION_PHRASES 0x41400304L
#define REBEL_CONVERSATION_PHRASES 0x41400404L
#define YEHAT_COLOR_MAP 0x41400504L
