/* This file was auto-generated by the gen_resfiles utility and
   should not be edited directly.  Modify the master resource list
   instead and regenerate. */

#define UTWIG_MUSIC "comm.utwig.music"
#define UTWIG_ULTRON_MUSIC "comm.utwig.ultron.music"
