/* This file was auto-generated by the gen_resfiles utility and
   should not be edited directly.  Modify the master resource list
   instead and regenerate. */

#define ZOQFOTPIK_ICON_MASK_PMAP_ANIM 0x5ae00302L
#define ZOQFOTPIK_MICON_MASK_PMAP_ANIM 0x5ae00402L
#define ZOQFOTPIK_BIG_MASK_PMAP_ANIM 0x5ae00502L
#define ZOQFOTPIK_MED_MASK_PMAP_ANIM 0x5ae00602L
#define ZOQFOTPIK_SML_MASK_PMAP_ANIM 0x5ae00702L
#define SPIT_BIG_MASK_PMAP_ANIM 0x5ae00802L
#define SPIT_MED_MASK_PMAP_ANIM 0x5ae00902L
#define SPIT_SML_MASK_PMAP_ANIM 0x5ae00a02L
#define STINGER_BIG_MASK_PMAP_ANIM 0x5ae00b02L
#define STINGER_MED_MASK_PMAP_ANIM 0x5ae00c02L
#define STINGER_SML_MASK_PMAP_ANIM 0x5ae00d02L
#define ZOQFOTPIK_CAPTAIN_MASK_PMAP_ANIM 0x5ae00e02L
