/* This file was auto-generated by the gen_resfiles utility and
   should not be edited directly.  Modify the master resource list
   instead and regenerate. */

#define REBEL_MUSIC "comm.yehat.rebel.music"
#define YEHAT_MUSIC "comm.yehat.music"
