/* This file was auto-generated by the gen_resfiles utility and
   should not be edited directly.  Modify the master resource list
   instead and regenerate. */

#define UMGAH_CONVERSATION_PHRASES "comm.umgah.dialogue"
#define UMGAH_COLOR_MAP "comm.umgah.colortable"
