/* This file was auto-generated by the gen_resfiles utility and
   should not be edited directly.  Modify the master resource list
   instead and regenerate. */

#define UMGAH_CONVERSATION_PHRASES 0x40c00204L
#define UMGAH_COLOR_MAP 0x40c00304L
