/* This file was auto-generated by the gen_resfiles utility and
   should not be edited directly.  Modify the master resource list
   instead and regenerate. */

#define UTWIG_MUSIC 0x41000006L
#define UTWIG_ULTRON_MUSIC 0x41000106L
