/* This file was auto-generated by the gen_resfiles utility and
   should not be edited directly.  Modify the master resource list
   instead and regenerate. */

#define UTWIG_CONVERSATION_PHRASES "comm.utwig.dialogue"
#define UTWIG_COLOR_MAP "comm.utwig.colortable"
