/* This file was auto-generated by the gen_resfiles utility and
   should not be edited directly.  Modify the master resource list
   instead and regenerate. */

#define MMRNMHRM_ICON_MASK_PMAP_ANIM "ship.mmrnmhrm.icons"
#define MMRNMHRM_MICON_MASK_PMAP_ANIM "ship.mmrnmhrm.meleeicons"
#define MMRNMHRM_BIG_MASK_PMAP_ANIM "ship.mmrnmhrm.graphics.mmrnmhrm.large"
#define MMRNMHRM_MED_MASK_PMAP_ANIM "ship.mmrnmhrm.graphics.mmrnmhrm.medium"
#define MMRNMHRM_SML_MASK_PMAP_ANIM "ship.mmrnmhrm.graphics.mmrnmhrm.small"
#define TORP_BIG_MASK_PMAP_ANIM "ship.mmrnmhrm.graphics.torp.large"
#define TORP_MED_MASK_PMAP_ANIM "ship.mmrnmhrm.graphics.torp.medium"
#define TORP_SML_MASK_PMAP_ANIM "ship.mmrnmhrm.graphics.torp.small"
#define YWING_BIG_MASK_PMAP_ANIM "ship.mmrnmhrm.graphics.ywing.large"
#define YWING_MED_MASK_PMAP_ANIM "ship.mmrnmhrm.graphics.ywing.medium"
#define YWING_SML_MASK_PMAP_ANIM "ship.mmrnmhrm.graphics.ywing.small"
#define MMRNMHRM_CAPTAIN_MASK_PMAP_ANIM "ship.mmrnmhrm.graphics.captain"
