/* This file was auto-generated by the gen_resfiles utility and
   should not be edited directly.  Modify the master resource list
   instead and regenerate. */

#define DRUUGE_CONVERSATION_PHRASES "comm.druuge.dialogue"
#define DRUUGE_COLOR_MAP "comm.druuge.colortable"
