/* This file was auto-generated by the gen_resfiles utility and
   should not be edited directly.  Modify the master resource list
   instead and regenerate. */

#define ILWRATH_CONVERSATION_PHRASES 0x3f200204L
#define ILWRATH_COLOR_MAP 0x3f200304L
