/* This file was auto-generated by the gen_resfiles utility and
   should not be edited directly.  Modify the master resource list
   instead and regenerate. */

#define BLACKURQ_COLOR_MAP "comm.kohrah.colortable"
#define BLACKURQ_CONVERSATION_PHRASES "comm.kohrah.dialogue"
