/* This file was auto-generated by the gen_resfiles utility and
   should not be edited directly.  Modify the master resource list
   instead and regenerate. */

#define VUX_COLOR_MAP "comm.vux.colortable"
#define VUX_CONVERSATION_PHRASES "comm.vux.dialogue"
