/* This file was auto-generated by the gen_resfiles utility and
   should not be edited directly.  Modify the master resource list
   instead and regenerate. */

#define VUX_CONVERSATION_PHRASES 0x41200204L
#define VUX_COLOR_MAP 0x41200304L
