/* This file was auto-generated by the gen_resfiles utility and
   should not be edited directly.  Modify the master resource list
   instead and regenerate. */

#define SYREEN_ICON_MASK_PMAP_ANIM 0x5a000302L
#define SYREEN_MICON_MASK_PMAP_ANIM 0x5a000402L
#define SYREEN_BIG_MASK_PMAP_ANIM 0x5a000502L
#define SYREEN_MED_MASK_PMAP_ANIM 0x5a000602L
#define SYREEN_SML_MASK_PMAP_ANIM 0x5a000702L
#define DAGGER_BIG_MASK_PMAP_ANIM 0x5a000802L
#define DAGGER_MED_MASK_PMAP_ANIM 0x5a000902L
#define DAGGER_SML_MASK_PMAP_ANIM 0x5a000a02L
#define SYREEN_CAPTAIN_MASK_PMAP_ANIM 0x5a000b02L
