/* This file was auto-generated by the gen_resfiles utility and
   should not be edited directly.  Modify the master resource list
   instead and regenerate. */

#define DAGGER_BIG_MASK_PMAP_ANIM "ship.syreen.graphics.dagger.large"
#define DAGGER_MED_MASK_PMAP_ANIM "ship.syreen.graphics.dagger.medium"
#define DAGGER_SML_MASK_PMAP_ANIM "ship.syreen.graphics.dagger.small"
#define SYREEN_BIG_MASK_PMAP_ANIM "ship.syreen.graphics.syreen.large"
#define SYREEN_CAPTAIN_MASK_PMAP_ANIM "ship.syreen.graphics.captain"
#define SYREEN_ICON_MASK_PMAP_ANIM "ship.syreen.icons"
#define SYREEN_MED_MASK_PMAP_ANIM "ship.syreen.graphics.syreen.medium"
#define SYREEN_MICON_MASK_PMAP_ANIM "ship.syreen.meleeicons"
#define SYREEN_SML_MASK_PMAP_ANIM "ship.syreen.graphics.syreen.small"
