/* This file was auto-generated by the gen_resfiles utility and
   should not be edited directly.  Modify the master resource list
   instead and regenerate. */

#define SLYLANDRO_ICON_MASK_PMAP_ANIM 0x59a00302L
#define SLYLANDRO_MICON_MASK_PMAP_ANIM 0x59a00402L
#define SLYLANDRO_BIG_MASK_PMAP_ANIM 0x59a00502L
#define SLYLANDRO_MED_MASK_PMAP_ANIM 0x59a00602L
#define SLYLANDRO_SML_MASK_PMAP_ANIM 0x59a00702L
#define SLYLANDRO_CAPTAIN_MASK_PMAP_ANIM 0x59a00802L
