/* This file was auto-generated by the gen_resfiles utility and
   should not be edited directly.  Modify the master resource list
   instead and regenerate. */

#define SHOFIXTI_ICON_MASK_PMAP_ANIM "ship.shofixti.icons"
#define SHOFIXTI_MICON_MASK_PMAP_ANIM "ship.shofixti.meleeicons"
#define SHOFIXTI_BIG_MASK_PMAP_ANIM "ship.shofixti.graphics.shofixti.large"
#define SHOFIXTI_MED_MASK_PMAP_ANIM "ship.shofixti.graphics.shofixti.medium"
#define SHOFIXTI_SML_MASK_PMAP_ANIM "ship.shofixti.graphics.shofixti.small"
#define DESTRUCT_BIG_MASK_ANIM "ship.shofixti.graphics.destruct.large"
#define DESTRUCT_MED_MASK_ANIM "ship.shofixti.graphics.destruct.medium"
#define DESTRUCT_SML_MASK_ANIM "ship.shofixti.graphics.destruct.small"
#define SHOFIXTI_CAPTAIN_MASK_PMAP_ANIM "ship.shofixti.graphics.captain"
#define OLDSHOF_BIG_MASK_PMAP_ANIM "ship.shofixti.graphics.oldshof.large"
#define OLDSHOF_MED_MASK_PMAP_ANIM "ship.shofixti.graphics.oldshof.medium"
#define OLDSHOF_SML_MASK_PMAP_ANIM "ship.shofixti.graphics.oldshof.small"
#define OLDSHOF_CAPTAIN_MASK_PMAP_ANIM "ship.shofixti.graphics.oldcaptain"
#define DART_BIG_MASK_PMAP_ANIM "ship.shofixti.graphics.missile.large"
#define DART_MED_MASK_PMAP_ANIM "ship.shofixti.graphics.missile.medium"
#define DART_SML_MASK_PMAP_ANIM "ship.shofixti.graphics.missile.small"
