/* This file was auto-generated by the gen_resfiles utility and
   should not be edited directly.  Modify the master resource list
   instead and regenerate. */

#define SPATHI_COLOR_MAP "comm.spathi.colortable"
#define SPATHI_CONVERSATION_PHRASES "comm.spathi.dialogue"
#define SPATHI_HOME_COLOR_MAP "comm.safeones.colortable"
#define SPATHI_HOME_CONVERSATION_PHRASES "comm.safeones.dialogue"
