//Copyright Paul Reiche, Fred Ford. 1992-2002

/*
 *  This program is free software; you can redistribute it and/or modify
 *  it under the terms of the GNU General Public License as published by
 *  the Free Software Foundation; either version 2 of the License, or
 *  (at your option) any later version.
 *
 *  This program is distributed in the hope that it will be useful,
 *  but WITHOUT ANY WARRANTY; without even the implied warranty of
 *  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *  GNU General Public License for more details.
 *
 *  You should have received a copy of the GNU General Public License
 *  along with this program; if not, write to the Free Software
 *  Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA 02111-1307, USA.
 */

#ifndef _STRINGS_H
#define _STRINGS_H

enum
{
	null_phrase,
	killed_fwiffo,
	fwiffo_fine,
	we_attack_again,
	bye_no_ally_offer,
	bye_angry_spathi,
	why_dont_you_do_it,
	we_apologize,
	we_are_vindicator0,
	we_are_vindicator1,
	we_are_vindicator2,
	gort_merenga,
	guph_florp,
	pleeese,
	wagngl_fthagn,
	screw_password,
	good_password,
	what_do_i_get,
	spathi_on_pluto,
	hostage,
	we_come_in_peace,
	misunderstanding,
	give_us_resources,
	resources_please,
	bye_ally,
	what_about_hierarchy,
	what_about_history,
	what_about_alliance,
	what_about_other,
	what_about_precursors,
	enough_info,
	little_mistake,
	bye_before_party,
	something_fishy,
	surrender,
	surrender_or_die,
	hand_in_friendship,
	stronger,
	yes_we_are,
	how_prove,
	share_info,
	prove_strength,
	what_test,
	think_more,
	tell_evil,
	i_accept,
	talk_test,
	already_got_them,
	too_dangerous,
	killed_them_all_1,
	killed_them_all_2,
	zapped_a_few,
	no_landing,
	saw_creatures,
	bye_from_party_1,
	bye_from_party_2,
	bye_from_party_3,
	deals_a_deal,
	how_long,
	reneging,
	return_beasts,
	minds_and_might,
	fellowship,
	do_as_we_say,
	whats_up,
	like_some_info
};

enum
{
	NULL_PHRASE,
	POOR_FWIFFO,
	NOT_LIKELY,
	WE_FIGHT_AGAIN,
	GOODBYE_NO_ALLY_OFFER,
	GOODBYE_ANGRY_SPATHI,
	WE_WONT_BECAUSE,
	MEAN_GUYS_RETURN,
	DONT_BELIEVE,
	HELLO_AGAIN,
	HATE_YOU_FOREVER,
	WHAT_IS_PASSWORD,
	WHAT_IS_PASSWORD_AGAIN,
	WRONG_PASSWORD,
	NO_PASSWORD,
	YOU_GET_TO_LIVE,
	YES_GOOD_PASSWORD,
	WHERE_SPATHI,
	GUN_TO_HEAD,
	OF_COURSE,
	KILLED_SPATHI,
	JUST_MISUNDERSTANDING,
	NO_RESOURCES,
	SORRY_NO_RESOURCES,
	GOODBYE_ALLY,
	OK_ENOUGH_INFO,
	ABOUT_HIERARCHY,
	ABOUT_HISTORY,
	ABOUT_ALLIANCE,
	ABOUT_OTHER,
	ABOUT_PRECURSORS,
	BIG_MISTAKE,
	QUEST_AGAIN,
	GOODBYE_BEFORE_PARTY,
	GOOD_START,
	NOTHING_FISHY,
	NO_SURRENDER,
	DEFEND_OURSELVES,
	TOO_AFRAID,
	YOURE_NOT,
	NO_YOURE_NOT,
	BETTER_IDEA,
	NO_INFO,
	WE_UNDERSTAND,
	YOUR_BEHAVIOR,
	BEFORE_ACCEPT,
	WIPE_EVIL,
	COWARD,
	AWAIT_RETURN,
	EARLY_BIRD_CHECK,
	NOT_SURPRISED,
	TEST_AGAIN,
	WE_AGREE,
	HOW_GO_EFFORTS,
	WILL_CHECK_1,
	WILL_CHECK_2,
	RETURN_COMPLETE,
	MUST_DESTROY_ALL,
	YOU_FORTUNATE,
	YOU_LIED_1,
	YOU_LIED_2,
	GOODBYE_FROM_PARTY,
	MUST_PARTY_1,
	MUST_PARTY_2,
	MUST_PARTY_3,
	WAIT_A_WHILE,
	TEN_YEARS,
	ADULT_VIEW,
	WHAT_RELATIONSHIP,
	HUH,
	WHAT,
	DEPART_FOR_EARTH,
	HELLO_ALLIES_1,
	HELLO_ALLIES_2,
	HELLO_ALLIES_3,
	GENERAL_INFO_1,
	GENERAL_INFO_2,
	GENERAL_INFO_3,
	GENERAL_INFO_4,
	GENERAL_INFO_5,
	WHAT_ABOUT
};

#endif /* _STRINGS_H */
