/* This file was auto-generated by the gen_resfiles utility and
   should not be edited directly.  Modify the master resource list
   instead and regenerate. */

#define UMGAH_ICON_MASK_PMAP_ANIM 0x5a400302L
#define UMGAH_MICON_MASK_PMAP_ANIM 0x5a400402L
#define UMGAH_BIG_MASK_PMAP_ANIM 0x5a400502L
#define UMGAH_MED_MASK_PMAP_ANIM 0x5a400602L
#define UMGAH_SML_MASK_PMAP_ANIM 0x5a400702L
#define SPRITZ_MASK_PMAP_ANIM 0x5a400802L
#define CONE_BIG_MASK_ANIM 0x5a400902L
#define CONE_MED_MASK_ANIM 0x5a400a02L
#define CONE_SML_MASK_ANIM 0x5a400b02L
#define UMGAH_CAPTAIN_MASK_PMAP_ANIM 0x5a400c02L
