/* This file was auto-generated by the gen_resfiles utility and
   should not be edited directly.  Modify the master resource list
   instead and regenerate. */

#define ILWRATH_ICON_MASK_PMAP_ANIM 0x58600302L
#define ILWRATH_MICON_MASK_PMAP_ANIM 0x58600402L
#define ILWRATH_BIG_MASK_PMAP_ANIM 0x58600502L
#define ILWRATH_MED_MASK_PMAP_ANIM 0x58600602L
#define ILWRATH_SML_MASK_PMAP_ANIM 0x58600702L
#define FIRE_BIG_MASK_PMAP_ANIM 0x58600802L
#define FIRE_MED_MASK_PMAP_ANIM 0x58600902L
#define FIRE_SML_MASK_PMAP_ANIM 0x58600a02L
#define ILWRATH_CAPTAIN_MASK_PMAP_ANIM 0x58600b02L
