/* This file was auto-generated by the gen_resfiles utility and
   should not be edited directly.  Modify the master resource list
   instead and regenerate. */

#define ILWRATH_RACE_STRINGS "ship.ilwrath.text"
