/* This file was auto-generated by the gen_resfiles utility and
   should not be edited directly.  Modify the master resource list
   instead and regenerate. */

#define GOB_BIG_MASK_PMAP_ANIM "ship.supox.graphics.gob.large"
#define GOB_MED_MASK_PMAP_ANIM "ship.supox.graphics.gob.medium"
#define GOB_SML_MASK_PMAP_ANIM "ship.supox.graphics.gob.small"
#define SUPOX_BIG_MASK_PMAP_ANIM "ship.supox.graphics.supox.large"
#define SUPOX_CAPTAIN_MASK_PMAP_ANIM "ship.supox.graphics.captain"
#define SUPOX_ICON_MASK_PMAP_ANIM "ship.supox.icons"
#define SUPOX_MED_MASK_PMAP_ANIM "ship.supox.graphics.supox.medium"
#define SUPOX_MICON_MASK_PMAP_ANIM "ship.supox.meleeicons"
#define SUPOX_SML_MASK_PMAP_ANIM "ship.supox.graphics.supox.small"
