/* This file was auto-generated by the gen_resfiles utility and
   should not be edited directly.  Modify the master resource list
   instead and regenerate. */

#define ANDROSYNTH_ICON_MASK_PMAP_ANIM "ship.androsynth.icons"
#define ANDROSYNTH_MICON_MASK_PMAP_ANIM "ship.androsynth.meleeicons"
#define ANDROSYNTH_BIG_MASK_PMAP_ANIM "ship.androsynth.graphics.androsyn.large"
#define ANDROSYNTH_MED_MASK_PMAP_ANIM "ship.androsynth.graphics.androsyn.medium"
#define ANDROSYNTH_SML_MASK_PMAP_ANIM "ship.androsynth.graphics.androsyn.small"
#define BUBBLE_BIG_MASK_PMAP_ANIM "ship.androsynth.graphics.bubble.large"
#define BUBBLE_MED_MASK_PMAP_ANIM "ship.androsynth.graphics.bubble.medium"
#define BUBBLE_SML_MASK_PMAP_ANIM "ship.androsynth.graphics.bubble.small"
#define BLAZER_BIG_MASK_PMAP_ANIM "ship.androsynth.graphics.blazer.large"
#define BLAZER_MED_MASK_PMAP_ANIM "ship.androsynth.graphics.blazer.medium"
#define BLAZER_SML_MASK_PMAP_ANIM "ship.androsynth.graphics.blazer.small"
#define ANDROSYNTH_CAPT_MASK_PMAP_ANIM "ship.androsynth.graphics.captain"
