/* This file was auto-generated by the gen_resfiles utility and
   should not be edited directly.  Modify the master resource list
   instead and regenerate. */

#define PKUNK_CONVERSATION_PHRASES 0x3fa00204L
#define PKUNK_COLOR_MAP 0x3fa00304L
