/* This file was auto-generated by the gen_resfiles utility and
   should not be edited directly.  Modify the master resource list
   instead and regenerate. */

#define URQUAN_COLOR_MAP "comm.urquan.colortable"
#define URQUAN_CONVERSATION_PHRASES "comm.urquan.dialogue"
