/* This file was auto-generated by the gen_resfiles utility and
   should not be edited directly.  Modify the master resource list
   instead and regenerate. */

#define THRADD_CONVERSATION_PHRASES "comm.thraddash.dialogue"
#define THRADD_COLOR_MAP "comm.thraddash.colortable"
