/* This file was auto-generated by the gen_resfiles utility and
   should not be edited directly.  Modify the master resource list
   instead and regenerate. */

#define CONFUSE_BIG_MASK_PMAP_ANIM "ship.melnorme.graphics.confu.large"
#define CONFUSE_MED_MASK_PMAP_ANIM "ship.melnorme.graphics.confu.medium"
#define CONFUSE_SML_MASK_PMAP_ANIM "ship.melnorme.graphics.confu.small"
#define MELNORME_BIG_MASK_PMAP_ANIM "ship.melnorme.graphics.melnorme.large"
#define MELNORME_CAPTAIN_MASK_PMAP_ANIM "ship.melnorme.graphics.captain"
#define MELNORME_ICON_MASK_PMAP_ANIM "ship.melnorme.icons"
#define MELNORME_MED_MASK_PMAP_ANIM "ship.melnorme.graphics.melnorme.medium"
#define MELNORME_MICON_MASK_PMAP_ANIM "ship.melnorme.meleeicons"
#define MELNORME_SML_MASK_PMAP_ANIM "ship.melnorme.graphics.melnorme.small"
#define PUMPUP_BIG_MASK_PMAP_ANIM "ship.melnorme.graphics.pump.large"
#define PUMPUP_MED_MASK_PMAP_ANIM "ship.melnorme.graphics.pump.medium"
#define PUMPUP_SML_MASK_PMAP_ANIM "ship.melnorme.graphics.pump.small"
