/* This file was auto-generated by the gen_resfiles utility and
   should not be edited directly.  Modify the master resource list
   instead and regenerate. */

#define SLYLANDRO_COLOR_MAP "comm.slyhome.colortable"
#define SLYLANDRO_CONVERSATION_PHRASES "comm.slyhome.dialogue"
