/* This file was auto-generated by the gen_resfiles utility and
   should not be edited directly.  Modify the master resource list
   instead and regenerate. */

#define SPATHI_HOME_PMAP_ANIM "comm.spahome.graphics"
#define SPATHI_PMAP_ANIM "comm.spathi.graphics"
