/* This file was auto-generated by the gen_resfiles utility and
   should not be edited directly.  Modify the master resource list
   instead and regenerate. */

#define SPATHI_PMAP_ANIM 0x40200802L
#define SPATHI_HOME_PMAP_ANIM 0x40200902L
