/* This file was auto-generated by the gen_resfiles utility and
   should not be edited directly.  Modify the master resource list
   instead and regenerate. */

#define SPATHI_MUSIC 0x40200006L
#define SPAHOME_MUSIC 0x40200106L
#define FWIFFO_MUSIC 0x40200206L
