/* This file was auto-generated by the gen_resfiles utility and
   should not be edited directly.  Modify the master resource list
   instead and regenerate. */

#define FWIFFO_MUSIC "comm.spafwiff.music"
#define SPAHOME_MUSIC "comm.spahome.music"
#define SPATHI_MUSIC "comm.spathi.music"
