/* This file was auto-generated by the gen_resfiles utility and
   should not be edited directly.  Modify the master resource list
   instead and regenerate. */

#define SPATHI_CONVERSATION_PHRASES 0x40200404L
#define SPATHI_HOME_COLOR_MAP 0x40200504L
#define SPATHI_HOME_CONVERSATION_PHRASES 0x40200604L
#define SPATHI_COLOR_MAP 0x40200704L
