/* This file was auto-generated by the gen_resfiles utility and
   should not be edited directly.  Modify the master resource list
   instead and regenerate. */

#define URQUAN_CONVERSATION_PHRASES 0x40e00204L
#define URQUAN_COLOR_MAP 0x40e00304L
