/* This file was auto-generated by the gen_resfiles utility and
   should not be edited directly.  Modify the master resource list
   instead and regenerate. */

#define ZOQFOTPIK_CONVERSATION_PHRASES 0x41600204L
#define ZOQFOTPIK_COLOR_MAP 0x41600304L
