/* This file was auto-generated by the gen_resfiles utility and
   should not be edited directly.  Modify the master resource list
   instead and regenerate. */

#define MYCON_ICON_MASK_PMAP_ANIM "ship.mycon.icons"
#define MYCON_MICON_MASK_PMAP_ANIM "ship.mycon.meleeicons"
#define MYCON_BIG_MASK_PMAP_ANIM "ship.mycon.graphics.mycon.large"
#define MYCON_MED_MASK_PMAP_ANIM "ship.mycon.graphics.mycon.medium"
#define MYCON_SML_MASK_PMAP_ANIM "ship.mycon.graphics.mycon.small"
#define PLASMA_BIG_MASK_PMAP_ANIM "ship.mycon.graphics.plasma.large"
#define PLASMA_MED_MASK_PMAP_ANIM "ship.mycon.graphics.plasma.medium"
#define PLASMA_SML_MASK_PMAP_ANIM "ship.mycon.graphics.plasma.small"
#define MYCON_CAPTAIN_MASK_PMAP_ANIM "ship.mycon.graphics.captain"
