/* This file was auto-generated by the gen_resfiles utility and
   should not be edited directly.  Modify the master resource list
   instead and regenerate. */

#define SHOFIXTI_CONVERSATION_PHRASES 0x3fc00204L
#define SHOFIXTI_COLOR_MAP 0x3fc00304L
