/* This file was auto-generated by the gen_resfiles utility and
   should not be edited directly.  Modify the master resource list
   instead and regenerate. */

#define SHOFIXTI_COLOR_MAP "comm.shofixti.colortable"
#define SHOFIXTI_CONVERSATION_PHRASES "comm.shofixti.dialogue"
