/* This file was auto-generated by the gen_resfiles utility and
   should not be edited directly.  Modify the master resource list
   instead and regenerate. */

#define BLACKURQ_PMAP_ANIM 0x3ea00402L
