/* This file was auto-generated by the gen_resfiles utility and
   should not be edited directly.  Modify the master resource list
   instead and regenerate. */

#define CHMMR_ICON_MASK_PMAP_ANIM "ship.chmmr.icons"
#define CHMMR_MICON_MASK_PMAP_ANIM "ship.chmmr.meleeicons"
#define CHMMR_BIG_MASK_PMAP_ANIM "ship.chmmr.graphics.chmmr.large"
#define CHMMR_MED_MASK_PMAP_ANIM "ship.chmmr.graphics.chmmr.medium"
#define CHMMR_SML_MASK_PMAP_ANIM "ship.chmmr.graphics.chmmr.small"
#define MUZZLE_BIG_MASK_PMAP_ANIM "ship.chmmr.graphics.muz.large"
#define MUZZLE_MED_MASK_PMAP_ANIM "ship.chmmr.graphics.muz.medium"
#define MUZZLE_SML_MASK_PMAP_ANIM "ship.chmmr.graphics.muz.small"
#define SATELLITE_BIG_MASK_PMAP_ANIM "ship.chmmr.graphics.sat.large"
#define SATELLITE_MED_MASK_PMAP_ANIM "ship.chmmr.graphics.sat.medium"
#define SATELLITE_SML_MASK_PMAP_ANIM "ship.chmmr.graphics.sat.small"
#define CHMMR_CAPTAIN_MASK_PMAP_ANIM "ship.chmmr.graphics.captain"
