/* This file was auto-generated by the gen_resfiles utility and
   should not be edited directly.  Modify the master resource list
   instead and regenerate. */

#define SLYLAND_COLOR_MAP "comm.slylandro.colortable"
#define SLYLAND_CONVERSATION_PHRASES "comm.slylandro.dialogue"
