/* This file was auto-generated by the gen_resfiles utility and
   should not be edited directly.  Modify the master resource list
   instead and regenerate. */

#define SUPOX_CONVERSATION_PHRASES 0x40400204L
#define SUPOX_COLOR_MAP 0x40400304L
