/* This file was auto-generated by the gen_resfiles utility and
   should not be edited directly.  Modify the master resource list
   instead and regenerate. */

#define STARCON_FONT "font.starcon"
#define TINY_FONT "font.tiny"
#define MICRO_FONT "font.micro"
#define LANDER_FONT "font.lander"
#define PLAYER_FONT "font.player"
#define PT13AA_FONT "credits.font.pt13"
#define PT17AA_FONT "credits.font.pt17"
#define PT45AA_FONT "credits.font.pt45"
