/* This file was auto-generated by the gen_resfiles utility and
   should not be edited directly.  Modify the master resource list
   instead and regenerate. */

#define HYPERSPACE_MUSIC "music.hyper"
#define QUASISPACE_MUSIC "music.arispace"
#define IP_MUSIC "music.space"
#define ORBIT1_MUSIC "music.orbit1"
#define ORBIT2_MUSIC "music.orbit2"
#define ORBIT3_MUSIC "music.orbit3"
#define ORBIT4_MUSIC "music.orbit4"
#define ORBIT5_MUSIC "music.orbit5"
#define MELEE_MUSIC "music.meleemenu"
#define REDALERT_MUSIC "music.redalert"
#define MAINMENU_MUSIC "music.mainmenu"
#define OUTFIT_MUSIC "music.outfit"
#define SHIPYARD_MUSIC "music.shipyard"
#define STARBASE_MUSIC "music.starbase"
#define BATTLE_MUSIC "music.battle"
#define CREDITS_MUSIC "music.credits"
