/* This file was auto-generated by the gen_resfiles utility and
   should not be edited directly.  Modify the master resource list
   instead and regenerate. */

#define MENU_SOUNDS 0x04000005L
#define GAME_SOUNDS 0x04200105L
#define LANDER_SOUNDS 0x05400205L
