/* This file was auto-generated by the gen_resfiles utility and
   should not be edited directly.  Modify the master resource list
   instead and regenerate. */

#define SPATHI_ICON_MASK_PMAP_ANIM "ship.spathi.icons"
#define SPATHI_MICON_MASK_PMAP_ANIM "ship.spathi.meleeicons"
#define SPATHI_BIG_MASK_PMAP_ANIM "ship.spathi.graphics.spathi.large"
#define SPATHI_MED_MASK_PMAP_ANIM "ship.spathi.graphics.spathi.medium"
#define SPATHI_SML_MASK_PMAP_ANIM "ship.spathi.graphics.spathi.small"
#define MISSILE_BIG_MASK_PMAP_ANIM "ship.spathi.graphics.missile.large"
#define MISSILE_MED_MASK_PMAP_ANIM "ship.spathi.graphics.missile.medium"
#define MISSILE_SML_MASK_PMAP_ANIM "ship.spathi.graphics.missile.small"
#define DISCRIM_BIG_MASK_PMAP_ANIM "ship.spathi.graphics.discrim.large"
#define DISCRIM_MED_MASK_PMAP_ANIM "ship.spathi.graphics.discrim.medium"
#define DISCRIM_SML_MASK_PMAP_ANIM "ship.spathi.graphics.discrim.small"
#define SPATHI_CAPTAIN_MASK_PMAP_ANIM "ship.spathi.graphics.captain"
