/* This file was auto-generated by the gen_resfiles utility and
   should not be edited directly.  Modify the master resource list
   instead and regenerate. */

#define UTWIG_ICON_MASK_PMAP_ANIM "ship.utwig.icons"
#define UTWIG_MICON_MASK_PMAP_ANIM "ship.utwig.meleeicons"
#define UTWIG_BIG_MASK_PMAP_ANIM "ship.utwig.graphics.utwig.large"
#define UTWIG_MED_MASK_PMAP_ANIM "ship.utwig.graphics.utwig.medium"
#define UTWIG_SML_MASK_PMAP_ANIM "ship.utwig.graphics.utwig.small"
#define LANCE_BIG_MASK_PMAP_ANIM "ship.utwig.graphics.lan.large"
#define LANCE_MED_MASK_PMAP_ANIM "ship.utwig.graphics.lan.medium"
#define LANCE_SML_MASK_PMAP_ANIM "ship.utwig.graphics.lan.small"
#define UTWIG_CAPTAIN_MASK_PMAP_ANIM "ship.utwig.graphics.captain"
