/* This file was auto-generated by the gen_resfiles utility and
   should not be edited directly.  Modify the master resource list
   instead and regenerate. */

#define ARILOU_PMAP_ANIM 0x3e800302L
#define ARILOU_COLOR_MAP 0x3e800404L
