/* This file was auto-generated by the gen_resfiles utility and
   should not be edited directly.  Modify the master resource list
   instead and regenerate. */

#define ARILOU_COLOR_MAP "comm.arilou.colortable"
#define ARILOU_PMAP_ANIM "comm.arilou.graphics"
