/* This file was auto-generated by the gen_resfiles utility and
   should not be edited directly.  Modify the master resource list
   instead and regenerate. */

#define YEHAT_ICON_MASK_PMAP_ANIM 0x5ac00302L
#define YEHAT_MICON_MASK_PMAP_ANIM 0x5ac00402L
#define YEHAT_BIG_MASK_PMAP_ANIM 0x5ac00502L
#define YEHAT_MED_MASK_PMAP_ANIM 0x5ac00602L
#define YEHAT_SML_MASK_PMAP_ANIM 0x5ac00702L
#define YEHAT_CANNON_BIG_MASK_PMAP_ANIM 0x5ac00802L
#define YEHAT_CANNON_MED_MASK_PMAP_ANIM 0x5ac00902L
#define YEHAT_CANNON_SML_MASK_PMAP_ANIM 0x5ac00a02L
#define SHIELD_BIG_MASK_ANIM 0x5ac00b02L
#define SHIELD_MED_MASK_ANIM 0x5ac00c02L
#define SHIELD_SML_MASK_ANIM 0x5ac00d02L
#define YEHAT_CAPTAIN_MASK_PMAP_ANIM 0x5ac00e02L
