/* This file was auto-generated by the gen_resfiles utility and
   should not be edited directly.  Modify the master resource list
   instead and regenerate. */

#define YEHAT_VICTORY_SONG 0x5ac00006L
