/* This file was auto-generated by the gen_resfiles utility and
   should not be edited directly.  Modify the master resource list
   instead and regenerate. */

#define THRADDASH_RACE_STRINGS 0x5a200104L
